name: wifi_connector
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.2

dependencies:
  camera: ^0.12.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_mlkit_text_recognition: ^0.17.1
  image: ^4.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
